Add chattering prevention
sago35/tinygo-keyboard pull request #13
Opened 2023-09-15 14:40 UTC by ehime-iyokan

チャタリング防止のため、キーが押されてから、離されるまでの間に待機する処理を追加。
待機時間は大まかな数値である。現状は機材がないことにより、実際の電圧の変化を見ることができないため。

2023-09-15 14:59 UTC, sago35 commented on keyboard.go
> +				time.Sleep(40 * time.Millisecond)
Thanks for your contoribution.

Don't put the blocking operation in here.
When quickly releasing some keys, performance is significantly degraded.

We need to wait without Blocking.

2023-10-09 03:45 UTC, ehime-iyokan commented
Changed a wait process without Blocking.
```We need to wait without Blocking```
* https://github.com/ehime-iyokan/tinygo-keyboard/tree/cc56fae3478ceffb13572a5baed5877752f9432a

However, the following two tasks are necessary.
1. Confirm that chattering does not occur on keyboards where chattering occurs when the tinygo-keyboard cycle is 10[ms].
   In my environment, chattering does not occur when tinygo-keyboard cycle is 10[ms], so I have only checked the operation when tinygo-keyboard cycle is 3[ms].
2. Implement chattering countermeasures for keyboards other than kbduplexmatrix.go.
  kbsquaredmatrix.go etc.

2023-10-10 14:42 UTC, ehime-iyokan commented
Changed a wait process without Blocking.
```We need to wait without Blocking```
* https://github.com/ehime-iyokan/tinygo-keyboard/compare/ccefd16..eb3362e

However, the following two tasks are necessary.
1. Confirm that chattering does not occur on keyboards where chattering occurs when the tinygo-keyboard cycle is 10[ms].
   In my environment, chattering does not occur when tinygo-keyboard cycle is 10[ms], so I have only checked the operation when tinygo-keyboard cycle is 3[ms].
2. Implement chattering countermeasures for keyboards other than kbduplexmatrix.go.
  kbsquaredmatrix.go etc.

2023-10-12 11:12 UTC, sago35 requested changes

2023-10-12 11:12 UTC, sago35 commented on kbduplexmatrix.go
> +					d.cycleCounter[idx]++
The following steps are likely to cause problems.
d.cycleCounter[idx] must be set back to 0

1. Press key A
2. Release key A
3. Press A key (d.cycleCounter[idx] is never cleared by case Press:)

2023-10-12 11:13 UTC, sago35 commented
@ehime-iyokan 
Also, it would be good to include chattering prevention when changing from None to NoneToPress.
This ensures consistent timing of press and release.

2023-10-17 15:07 UTC, ehime-iyokan commented on kbduplexmatrix.go
> +					d.cycleCounter[idx]++
Added process to set d.cycleCounter[idx] to 0 in the following commit
* https://github.com/sago35/tinygo-keyboard/pull/13/commits/7432e3e66e87248f9b8f2217fc9d30fb9a6e3fef

2023-10-30 00:28 UTC, sago35 approved these changes
LGTM

2023-10-30 00:29 UTC, merged